
@baseUrl = http://localhost:8005

### 1. Register new user (returns full user info)
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "fullName": "VoVanTu",
  "email": "t@hcmute.edu.vn",
  "password": "password123",
  "images": "profile.jpg"
}

### 2. Login user (returns JWT token)
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "tu@hcmute.edu.vn",
  "password": "password123"
}
